
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/stephan/.local/lib/python3.11/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The system is: Linux - 6.7.1-arch1-1 - x86_64
...
